### ISSUE TITLE
Support pp for large/complex structures

### ISSUE THREAD

**Issue by avdi** [JoshCheek/seeing_is_believing#44]
first off, this project is super, super cool. I'm now evaluating it to see if it would be a viable replacement for xmpfilter in RubyTapas.

One feature that I use a lot in xmpfilter is the difference between annotating the end of a line and annotating on the next line. In xmpfilter, if you annotate the following line, it switches to using `pp` indented output instead of `inspect` output. This is handy for showing the contents of large or nested data structures.

Here's an example using `xmpfilter`:

```ruby
h = {
  foo: 42,
  bar: {
    baz: 1,
    buz: 2,
    fuz: 3,
  },
  wibble: {
    magic_word: "xyzzy",
  }
}

h # => {:foo=>42, :bar=>{:baz=>1, :buz=>2, :fuz=>3}, :wibble=>{:magic_word=>"xyzzy"}}

h
# => {:foo=>42,
#     :bar=>{:baz=>1, :buz=>2, :fuz=>3},
#     :wibble=>{:magic_word=>"xyzzy"}}
```

Is this a possibility in SIB?

**Comment by JoshCheek** [comment]
If you're hitting annoying issues with versions of Ruby / Parser, I released [beta4](http://rubygems.org/gems/seeing_is_believing/versions/3.0.0.beta.4) which has an update that should fix this. A few other bugs will go away, too. Not all of them, though.

**Comment by JoshCheek** [comment]
Hi, Avdi.

[beta5](https://rubygems.org/gems/seeing_is_believing/versions/3.0.0.beta.5) is out. It should be stable enough to release as v3.0, but I'm going to wait a bit anyway, b/c I'd like to polish up some editor integrations so it's easier for people to be excited about it. If you wouldn't mind using it and letting me know if you hit any issues, I'd appreciate it.


## Some things to look forward to

* It handles all the Ruby 2.2 syntax.
* It now has only one dependency: `Parser`
* There is only one known parsing bug, which should probably be a syntax error, anyway.
* Handles `__ENCODING__` macro
* Handles `exit!`
* Intelligent identification of `__DATA__` segment
* Help examples ar updated
* If you clean the document with the xmpfilter flag set, it will clean the values, but leave the annotations:
  ```ruby
  $ cat f.rb
    {foo: 42, bar: {baz: 1, buz: 2, fuz: 3}, wibble: {magic_word: "xyzzy"}} # => {:foo=>42, :bar=>{:baz=>1, :buz=>2, :fuz=>3}, :wibble=>{:magic_word=>"xyzzy"}}
    # => {:foo=>42,
    #     :bar=>{:baz=>1, :buz=>2, :fuz=>3},
    #     :wibble=>{:magic_word=>"xyzzy"}}
    # >> stdout
    # !> stderr
    # ~> exception

  $ seeing_is_believing --xmpfilter-style --clean f.rb
    {foo: 42, bar: {baz: 1, buz: 2, fuz: 3}, wibble: {magic_word: "xyzzy"}} # =>
    # =>
  ```
* Handles multiple invocations of multi-line output. The format is taken from xmpfilter, but if you wind up using this and have a preference for an alternate one, let me know, b/c I'm not super in love with it. I was thinking maybe another value marker instead of the comma.

  ```ruby
  2.times do
    {foo: 42, bar: {baz: 1, buz: 2, fuz: 3}, wibble: {magic_word: "xyzzy"}}
    # => {:foo=>42,
    #     :bar=>{:baz=>1, :buz=>2, :fuz=>3},
    #     :wibble=>{:magic_word=>"xyzzy"}}
    #    ,{:foo=>42,
    #     :bar=>{:baz=>1, :buz=>2, :fuz=>3},
    #     :wibble=>{:magic_word=>"xyzzy"}}
  end
  ```
* It can handle repeated invocations of multiline inspections with leading whitespace. It does this by replacing the first space with a nonbreaking space. Which is a little questionable, but seemed to be the least invasive of my ideas for how to deal with it.
  ```ruby
  bst = Object.new
  def bst.inspect
    "   4\n"\
    " 2   6\n"\
    "1 3 5 7\n"
  end
  bst
  # =>    4
  #     2   6
  #    1 3 5 7
  ```
* It handles `BEGIN` and `END`
  ```ruby
  p 1              # => 1
  END { p 2 }      # => 2
  p 3              # => 3
  BEGIN {
    p 4            # => 4
    BEGIN { p 5 }  # => 5
  }

  # >> 5
  # >> 4
  # >> 1
  # >> 3
  # >> 2
  ```
* It handles `exec`
  ```ruby
  puts "PARENT PID: #$$"                              # => nil
  ENV["AT_THE_ZOO"] = "hampsters journal frequently"  # => "hampsters journal frequently"

  exec 'bash', '-c', <<BASH
    env | grep ZOO
    echo CHILD PID $$
  BASH

  puts "we'll never get here"

  # >> PARENT PID: 26457
  # >> AT_THE_ZOO=hampsters journal frequently
  # >> CHILD PID 26457
  ```
* The output can be streamed in real-time. This means that if you were particularly good with your editor, you could do something like open a second window, and add the results there instead of interpolating them as comments. This would be a pretty slick interface, and would also give you instant feedback instead of having to wait until the end.    
  ![sib-streaming](https://s3.amazonaws.com/josh.cheek/images/scratch/sib-streaming.gif)


No Broken Windows
-----------------

If you uncover any on this version, please let me know. I think it is in a good spot right now and would like to keep it bug-free.

Deprecations:
-------------

These all still work, so-as not to break the interface. But since it's a major version change, I took the opportunity to choose more descriptive names for these flags.

* `--number-of-captures` is now `--max-line-captures`
* `--timeout` is now `--timeout-seconds` 
* `--shebang` is gone altogether (turns out you can figure out the correct Ruby with `RbConfig.ruby`)


Here are some things I'd probably do if you or anyone implied they wanted them
------------------------------------------------------------------------------

* Custom alignment strategies (e.g. align at 40 characters, but if you can't, fall back to chunk alignment)
* Alignments for xmpfilter (currently, it stays with whatever you've set)
* A specific format for multiple multiline outputs with xmpfilter
* A better solution to errors on lines with value markers (xmpfilter style), I just don't even know what would be correct here. The current solution is at least not-broken.
* Ability to use custom markers
* Ability to customize pp output. e.g. Internally, I'm using a data structure which is basically a conjunction of a hash and a struct. Its inspect was terrible, so I played with `pp` for a while until I got it to [look like this](https://cloud.githubusercontent.com/assets/77495/5771610/db8d5fa2-9cfd-11e4-81cf-dd02ea591aad.png) There's no reason we can't have things like 1.9 style hash keys, smarter word breaking, etc. If you like that, or generally want to play with the representation of anything, let me know. (note that you can use `-r` flag to require a file, so you could play with this yourself if you were interested)

**Comment by avdi** [comment]
This sounds spectacular! I've installed it on my RubyTapas VM so I'll be
putting it through its paces. I may just have to bind that --clean version
to a new keybinding.

Thank you!!

--
Avdi Grimm
http://avdi.org

**Comment by JoshCheek** [comment]
Closing this since v3 is released.
